### ISSUE TITLE
Threaded Messages

### ISSUE THREAD

**Issue by pvzig** [pvzig/SlackKit#100]
- [Docs: Threaded Messages](https://api.slack.com/docs/message-threading)

**Comment by johntmcintosh** [comment]
@pvzig I have just posted pull requests to SKCore and SKWebAPI which I think should cover what's necessary to add thread support.

**Comment by pvzig** [comment]
Completed with the following PRs:
https://github.com/SlackKit/SKRTMAPI/pull/3
https://github.com/SlackKit/SKWebAPI/pull/3
https://github.com/SlackKit/SKCore/pull/3
https://github.com/SlackKit/SKCore/pull/4
