### ISSUE TITLE
Missing WebAPI Methods

### ISSUE THREAD

**Issue by pvzig** [pvzig/SlackKit#102]
We're missing two reactions Web API endpoints:
- `reactions.get`
- `reactions.list`

**Comment by pvzig** [comment]
Done:
https://github.com/SlackKit/SKCore/commit/c6b41423222536528a606479c045afbe5607c04e
https://github.com/SlackKit/SKWebAPI/commit/0c5b3188d2c2ea5d52aba816614a95ab8b0df4a4
https://github.com/SlackKit/SKWebAPI/commit/461de5ecec219fd47a469a745aa67040f54b4f27

**Comment by tandinhle** [comment]
Missing endpoint:

- channels.join
