### ISSUE TITLE
Limited Response Middleware

### ISSUE THREAD

**Issue by jPaolantonio** [pvzig/SlackKit#111]
I'm working on a Slash command that needs access to information from the `WebhookRequest` to help determine the response.

My initial thought was to subclass `Middleware` in order to do this. While this will suit my needs, I wonder if it is better to generalize this approach.

Is there a reason the current implementation exists? Would there be interest in adding new middleware that supports this case?

**Comment by pvzig** [comment]
Hey James,

I imagine that this would be a pretty common use case - I think there would definitely be value in adding a new middleware that supports this case specifically.
