### ISSUE TITLE
Bot receives multiple messages

### ISSUE THREAD

**Issue by kmkrn** [pvzig/SlackKit#112]
I am building a chat bot using Swift and Xcode 8. The Slack client delegate function: 
`func received(_ message: Message, client: SlackClient){}
`
seems to be called multiple times. The bot builds answer based on incoming message, therefore the message from bot also gets printed more than once.

**Comment by pvzig** [comment]
Apologies for the late reply - I'd recommend upgrading to the `4.0.0` release. If you're still seeing issues after upgrading, please follow up here or open another issue.

Peter
