### ISSUE TITLE
Throw error when the message length exceeds the limit

### ISSUE THREAD

**Issue by kmkrn** [pvzig/SlackKit#114]
In Slack there's a limit for length of messages (4000 bytes). I'd been banging my head against the wall trying to figure out why my message is not being printed in chat when everything ran perfectly on console before guessing there might be a limit. No error was shown for that. Would it be a good idea to throw this kind of error?

**Comment by pvzig** [comment]
We should absolutely be throwing an error here. According to Slack's [docs](https://api.slack.com/methods/chat.postMessage#formatting):
> A single message should be no larger than 4,000 bytes.
