### ISSUE TITLE
Create channel WebAPI method

### ISSUE THREAD

**Issue by rafalwojcik** [pvzig/SlackKit#116]
I saw that there are a lot of missing WebAPI methods related to Slack documentation. Actually, to my project, I need just create a channel, so I will create PR to add this. I will try to follow code style and conventions that you are using through SlackKit. In free time maybe I will add more methods to match the Slack documentation.

Added PR: SlackKit/SKWebAPI#9

Should I also update documentation in SlackKit/SlackKit by PR? @pvzig

**Comment by rafalwojcik** [comment]
@pvzig, Of course, one file is missing sorry about that. I updated PR with this file and another method to invite a user to channel.

**Comment by rafalwojcik** [comment]
@pvzig Any feedback?

**Comment by pvzig** [comment]
Merged: https://github.com/SlackKit/SKWebAPI/pull/9
