### ISSUE TITLE
Swift 4 / Xcode 9 support

### ISSUE THREAD

**Issue by 4np** [pvzig/SlackKit#117]
Right now, following the steps to get started `SlackKit` does not seem to work with Swift 4 and its revised package manager.

**Comment by triple7** [comment]
Hi, I would like to add that opening in Xcode 9.x shows errors in some of the packages required for SlackKit (Swifter has 19 warnings and 3 errors which forbids me to compile). Is there a bleeding edge commit I can test with swift 4/xcode 9.x ?

Thanks

**Comment by pvzig** [comment]
I'd be happy to merge any PRs for upgrading to Swift 4.

It might be awhile before I can update everything personally as I've got a newborn baby at home occupying my time.

**Comment by pvzig** [comment]
Resolved in 4.1.0: https://github.com/SlackKit/SlackKit/releases/tag/4.1.0
