### ISSUE TITLE
Cannot connect to WebSocket on Linux

### ISSUE THREAD

**Issue by caiofbpa** [pvzig/SlackKit#119]
When I try to boot up the bot on Linux, it fails to connect to Slack with the following message:

```
WebSocket client could not connect: responseNotWebsocket
```

As I tried to debug what was happening, I found out that somehow when the WebSocketClient tried to upgrade the connection to a WebSocket connection, it gets a `404` response instead of the expected `101`. I couldn't figure out why, the URL and headers look correct, and a week ago the bot worked just fine.

Sorry to open this issue here, since I think the actual problem is somehow on ZewoGraveyard/WebSocketClient's code, but I also think SlackKit has to consider migrating away from Zewo's WebSocketClient due to it's lack of maintenance. It has literally been put into a Graveyard organisation.

**Comment by tomohisa** [comment]
Same things happen to me. I don't use Slack Kit but I use HTTPClient from Zewo. Hopefully you could make it though.

**Comment by caiofbpa** [comment]
Solved by https://github.com/SlackKit/SKRTMAPI/pull/9
