### ISSUE TITLE
Type 'SlackKit' does not conform to protocol 'RTMAdapter'

### ISSUE THREAD

**Issue by ihityouback** [pvzig/SlackKit#123]
After dependencies update a few days ago I've got the error:
 ```
Type 'SlackKit' does not conform to protocol 'RTMAdapter'
```
Error repeats even after fresh install.
Adding a stub for `connectionClosed(with error: Error, instance: SKRTMAPI)` method fixes the problem, but not sure that this is the proper solution (: 
Looks 

Is it only my problem or there some bug of SlackKit conformance to SKRTMAPI?
Thanks in advance!

**Comment by soleniacz** [comment]
There is a mismatch of entries of Cartfiles in subprojects. Searching solution myself right now.

Probably need to fork some of them and set == in few of them.

Because Carthage tries download newest when there is >= in Cartfile

**Comment by ihityouback** [comment]
@soleniacz I'm using SPM, but this problem apparently reproduces in all dependency managers.
In my situation, it will not help because I need a fix from last SKRTMAPI version

**Comment by soleniacz** [comment]
For those who want latest working SlackKit version. Carthage.
`github "SlackKit/SlackKit" == 4.0.7`
Don't leave version blank because Carthage will try to download the latest version from master where are incompatible changes.

**Comment by pvzig** [comment]
Apologies, working on getting everything updated to Swift 4 with bad dependency manager versioning. Should be squared away by this weekend.

**Comment by pvzig** [comment]
Resolved in 4.1.0 https://github.com/SlackKit/SlackKit/releases/tag/4.1.0
