### ISSUE TITLE
Issue with `slackFormatEscaping`

### ISSUE THREAD

**Issue by PoissonBallon** [pvzig/SlackKit#124]
Hi :)

I have some issues with the `slackFormatEscaping` function
When I use it I am unable to make mentions because it escape the characters but after when `URLQueryItem` convert params it encodes this to Percent-encoding

For the moment I have fork all the repositories to remove this function,
Am I wrong or Am i missing something ?

**Comment by PoissonBallon** [comment]
For more information, after remove `slackFormatEscaping` all work fine on OSX but not on linux I was able to fix the problem just with adding this : 
https://github.com/NoRespect/SKWebAPI/commit/6bf4528d53081ee28d4546a5110990d0b785a499
IMHO, I think it's better to do it here than to change the strings in the models :D 
I am obviously available to talk about it ;)

**Comment by pvzig** [comment]
Hey Vialatte,

Your solution looks great - do you want to PR the changes in your fork? Would be happy to merge.

Thanks!

**Comment by pvzig** [comment]
PRs merged, closing. Thanks!

**Comment by yhkaplan** [comment]
@PoissonBallon Thank you so much! This should help me too. @pvzig No hurry, but when do you plan on making a new release that includes the PRs above?

**Comment by pvzig** [comment]
@yhkaplan With Carthage or SPM you should pick up the latest versions of the updated dependencies with a clean build. Currently stuck on pushing updates to Cocoapods due to an issue with a dependency: https://github.com/httpswift/swifter/pull/293#issuecomment-373431850

**Comment by yhkaplan** [comment]
@pvzig Just what I needed, thanks!
