### ISSUE TITLE
Cannot receive messages when using OAuthConfig

### ISSUE THREAD

**Issue by guidomb** [pvzig/SlackKit#125]
Maybe I'm misunderstanding how `OAuthConfig` should be used but the following snippet does not work for me. I receive no messages.

```swift
import SlackKit

let bot = SlackKit()
let oauthConfig = OAuthConfig(clientID: "CLIENT_ID", clientSecret: "CLIENT_SECRET")
bot.addServer(oauth: oauthConfig)
bot.notificationForEvent(.message) { (event, _) in
    print("Message received")
}
RunLoop.main.run()
```

When I change it to using `bot.addRTMBotWithAPIToken` I start receiving messages. What is the proper way of authentication?

**Comment by pvzig** [comment]
You can use whichever best fits your needs, there is no one proper way to authenticate.

If you're using the OAuth setup, you'll need to authorize the Slack application you've created through the OAuth flow before you receive events. This [tutorial](https://api.slack.com/tutorials/app-creation-and-oauth) details what that setup looks like (in node, but the idea is the same).
