### ISSUE TITLE
Not running on Heroku

### ISSUE THREAD

**Issue by DanielCreagh** [pvzig/SlackKit#127]
```
Compile Swift Module 'SKCore' (27 sources)
remote: /app/tmp/cache/.build/checkouts/swifter.git--8340134586818345596/Sources/MimeTypes.swift:139:17: error: cannot convert value of type 'String' to type 'NSString' in coercion
remote:         return (self as NSString).mimeType()
remote:                 ^~~~
remote: error: terminated(1): /app/tmp/cache/swiftenv/versions/4.1/usr/bin/swift-build-tool -f /app/tmp/cache/.build/release.yaml main output:
remote:
```

prevents running SlackKit library on Heroku- seems like a massive blunder to me.  Any idea's when this will be fixed?

Great library seems a shame to not actually be able to use it in a real world scenario.

Keep up good work!

**Comment by pvzig** [comment]
Might be a Swift version issue, looks like you're building with Swift 4.1? Last verified against Swift 4.0, I'll have to look into 4.1 compatibility.

**Comment by pvzig** [comment]
Fixed here: https://github.com/SlackKit/SKServer/pull/4
