### ISSUE TITLE
Action with URL

### ISSUE THREAD

**Issue by ghost** [pvzig/SlackKit#128]
Hi guys, 
I am so excited that you have created an amazing lib for us. It is very useful.
However I am running into a problem where I cannot create a `Button` that is linked to a webpage 

According to this documentation, Slack API allows me to have a link button format 
https://api.slack.com/docs/message-attachments#attaching_links_to_messages
``` python
{
  "text": "<@W1A2BC3DD> approved your travel request. Book any airline you like by continuing below.",
  "channel": "C061EG9SL",
  "attachments": [
    {
      "fallback": "Book your flights at https://flights.example.com/book/r123456",
      "actions": [
        {
          "type": "button",
          "text": "Book flights 🛫",
          "url": "https://flights.example.com/book/r123456"
        }
      ]
    }
  ]
}
```

But seems like your contribution is not covered this feature yet which allows me to have an `url` 

![screen shot 2018-07-09 at 14 19 33](https://user-images.githubusercontent.com/16188265/42436149-36301278-8383-11e8-97e9-7777818abb14.png)

So, I would like to ask you about implementing this feature. I have implemented in my local machines and It worked very well and I think it will be more nice if you update it too.

Best Regards,
Shinriki Kenkai

**Comment by pvzig** [comment]
Thanks for the kind words Shinriki! Glad you're finding it useful.

If you have this working locally, would you mind PRing your changes? Would be happy to merge 🙂

**Comment by pvzig** [comment]
I've merged and released your PR - thanks!

[4.1.2](https://github.com/SlackKit/SKCore/releases/tag/4.1.2)
