### ISSUE TITLE
Got error message of SKWebAPI

### ISSUE THREAD

**Issue by ghost** [pvzig/SlackKit#129]
Hi,

I got an error message `slackFormatEscaping` which I have checked on your `SKwebAPI` repo you have alreay removed this out but I don't know that was really happening when I install `SlackKit` using `Pod`. It is still there. I have also remove the whole pod folder and install again but I got the same error.

### Install Pod
![image 2018-07-17 at 11 56 31 am](https://user-images.githubusercontent.com/16188265/42797561-fdcad7a0-89b9-11e8-94a5-abcc23144282.png)

### Podfile.lock
>  - SKClient (4.1.0):
>    - SKCore
>  - SKCore (4.1.2)
>  - SKRTMAPI (4.1.2):
>    - SKCore
>    - SKWebAPI
>    - Starscream
>  - SKServer (4.0.0):
>    - SKCore
>    - SKWebAPI
>    - Swifter
>  - SKWebAPI (4.1.2):
>    - SKCore
>  - SlackKit (4.1.0):
>    - SKClient
>    - SKCore
>    - SKRTMAPI
>    - SKServer

### File
![image 2018-07-17 at 11 56 54 am](https://user-images.githubusercontent.com/16188265/42797570-0456b0a8-89ba-11e8-9573-4e8fb78a6dd6.png)

By the way, when I performed `pod update` error also happened.

**Comment by crexista** [comment]
This problem maybe fixed on latest version 4.1.3 (https://github.com/SlackKit/SKWebAPI/commit/b5b303c7e5cdecd587499061a81128ef4d7ed3f1)

But SKWebAPI.podspec set versions 4.1.2...
https://github.com/SlackKit/SKWebAPI/blob/master/SKWebAPI.podspec#L3

**Comment by pvzig** [comment]
I've pushed the updated podspec for SKWebAPI, so running a `pod install` after updating should get you the latest. Thanks!
