### ISSUE TITLE
Not building in linux environment, doesn't proceed after some time

### ISSUE THREAD

**Issue by pshrinivas** [pvzig/SlackKit#131]
`root@ubuntu-s-1vcpu-1gb-blr1-01:~/hello-world# vapor build --verbose
Building Project ...
Updating https://github.com/vapor/websocket.git
Updating https://github.com/vapor/validation.git
Updating https://github.com/vapor/http.git
Updating https://github.com/vapor/database-kit.git
Updating https://github.com/vapor/fluent-sqlite.git
Updating https://github.com/vapor/service.git
Updating https://github.com/vapor/sqlite.git
Updating https://github.com/apple/swift-nio.git
Updating https://github.com/vapor/routing.git
Updating https://github.com/apple/swift-nio-ssl.git
Updating https://github.com/vapor/crypto.git
Updating https://github.com/vapor/sql.git
Updating https://github.com/apple/swift-nio-zlib-support.git
Updating https://github.com/vapor/template-kit.git
Updating https://github.com/vapor/url-encoded-form.git
Updating https://github.com/vapor/console.git
Updating https://github.com/apple/swift-nio-ssl-support.git
Updating https://github.com/vapor/multipart.git
Updating https://github.com/daltoniam/Starscream
Updating https://github.com/httpswift/swifter
Updating https://github.com/daltoniam/common-crypto-spm
Updating https://github.com/vapor/fluent.git
Updating https://github.com/vapor/vapor.git
Updating https://github.com/daltoniam/zlib-spm.git
Updating https://github.com/vapor/core.git
Updating https://github.com/SlackKit/SlackKit.git
Updating https://github.com/SlackKit/SKServer
Updating https://github.com/SlackKit/SKRTMAPI
Updating https://github.com/SlackKit/SKCore
Updating https://github.com/SlackKit/SKClient
Updating https://github.com/vapor/engine
Updating https://github.com/SlackKit/SKWebAPI
Updating https://github.com/vapor/random.git
Updating https://github.com/vapor/sockets.git
Updating https://github.com/vapor/tls.git
`

Gets hanged at this point and doesn't proceed further

Package.swift
`.package(url: "https://github.com/SlackKit/SlackKit.git", .upToNextMinor(from: "4.1.0"))`

works perfectly on MacOS environment but same fails on ubuntu 

env details 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by pvzig** [comment]
Apologies for the extremely delayed response. This should be resolved in the latest release.
