### ISSUE TITLE
Consolidating project repos

### ISSUE THREAD

**Issue by interstateone** [pvzig/SlackKit#135]
Hi! I’ve been trying out Slack bots and apps in Swift off and on since Swift became open source. SlackKit has always seemed like a good way to get started because it has a decent amount of coverage of their API. The name is good too 😄. Thanks for all of your work on this project. 

Recently I’ve been making some changes in a fork to add support for multiple `files` per event, and setting a custom status. I’d also like to take a swing at migrating to Codable. One thing that makes all of this a little bit tedious is having each part of SlackKit in a separate repo. `swift package edit` makes this sort of flow a little easier now but I think it could be simpler. I’m sure there was a reason for splitting things up, but wanted to see what you thought about consolidating the other repos into this one, while still exposing both the individual targets as libraries and a single SlackKit library with all targets. Do you think this would work?

**Comment by pvzig** [comment]
Hey Brandon,

Absolutely! It's actually at the top of my todo list for this project - the current organization makes development a real pain.

**Comment by interstateone** [comment]
That's great to hear, thanks! Is there anything I (or others) can do to help?

**Comment by pvzig** [comment]
Working on it on this branch: https://github.com/pvzig/SlackKit/tree/monorepo. Mostly done, just some minutiae around CocoaPods and Carthage + platform schemes left. The iOS targets should compile in Xcode and build with SPM.

If you wanted to take a look, I would love any feedback you have around making developing/contributing as easy as possible 😀

**Comment by interstateone** [comment]
I see that branch is merged now, so I'll close this issue. I haven't had a chance to update my project to test out master but I'll be sure to do so soon, and I have a few updates to submit PRs for. Thanks for doing this!
