### ISSUE TITLE
Unable to build with Swift Package Manager

### ISSUE THREAD

**Issue by ObscureBug** [pvzig/SlackKit#148]
Attempts to build recent versions of SlackKit fail when using SPM.

Using the following steps, building an application including SlackKit fails when specifying version 4.2.0 rather than 4.1.0 (which still works):

```
mkdir x6
cd x6
swift package init --type executable
```
_edit `Package.swift` to include dependencies_
```
swift package generate-xcodeproj
open x6.xcodeproj
```
_build project using Xcode UI_

```
$ swift --version
Apple Swift version 4.2.1 (swiftlang-1000.11.42 clang-1000.11.45.1)
Target: x86_64-apple-darwin18.2.0
```
Xcode Version 10.1 (10B61)

Build errors are in dependencies of packages required by SlackKit. e.g.
```
... x6/.build/checkouts/swift-nio-ssl.git--5028798909648298346/Sources/CNIOOpenSSL/include/c_nio_openssl.h:17:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
```

I see this problem on both of my systems.  Hopefully this isn't an embarrassing pilot error on my behalf.

[slackkit.bug.txt](https://github.com/pvzig/SlackKit/files/2899036/slackkit.bug.txt)

**Comment by pvzig** [comment]
It looks like you probably don't have the OpenSSL library it's expecting installed on your system (I need to update the readme ☹️).

Try installing it via homebrew: `brew install libressl`
Related vapor issue for more context: https://github.com/vapor/vapor/issues/1562

**Comment by ObscureBug** [comment]
I had considered trying to install whatever it complained about, but what has me confused is that if I clone/download SlackKit, I can build it within Xcode and produce the frameworks, etc. without it failing with these errors. (aka without installing OpenSSL, etc)

I would have expected either both methods to fail or both methods to work, or am I missing something?

I also didn't understand why this is a new dependency based on the changes.

I get nervous about hand installing external packages so as not to inadvertently create a runtime dependency on this stuff when shipping a binary that uses SlackKit.

**Comment by pvzig** [comment]
Totally understand your apprehension here, and I agree that having to install a system library to build using SPM is a bad compromise! Some additional context...

One of the changes I made in the new [Package.swift](https://github.com/pvzig/SlackKit/blob/master/Package.swift#L26) was to include the Vapor WebSocket dependency and build the [Vapor RTM conformer](https://github.com/pvzig/SlackKit/blob/master/SKRTMAPI/Sources/Conformers/VaporEngineRTM.swift), which is used when running SlackKit on linux, by default to make it easier for those folks to develop on the Mac. **This file is _only_ compiled and included when using SPM.**

The following modification to the Package file would revert this (untested):
```
let SKRTMAPI: Target = .target(name: "SKRTMAPI",
                               path: "SKRTMAPI/Sources",
                               exclude: ["SKRTMAPI/Sources/Conformers/VaporEngineRTM.swift"])

#if os(macOS)
SKRTMAPI.dependencies = [
    "SKCore",
    "SKWebAPI",
    "Starscream"
]
```

This will no longer be necessary when Swift 5 and the associated [swift-nio](https://github.com/apple/swift-nio) releases drop later this spring and swift-nio switches to using a vendored copy of BoringSSL (see: https://forums.swift.org/t/rfc-moving-swiftnio-ssl-to-boringssl/18280 - your timing is impeccable, looks like that [commit just hit](https://github.com/apple/swift-nio-ssl/commit/141ff46685b02095653654843f6b837690e41925)).

**Comment by ObscureBug** [comment]
Thanks for your solution.  I got a chance to test this yesterday, only one slight change was required:

```
let SKRTMAPI: Target = .target(name: "SKRTMAPI",
                               path: "SKRTMAPI/Sources",
                               exclude: ["Conformers/VaporEngineRTM.swift"])

#if os(macOS)
SKRTMAPI.dependencies = [
    "SKCore",
    "SKWebAPI",
    "Starscream"
]
```
