### ISSUE TITLE
`sendEphemeral` should have an equivalent `sendThreadedEphemeral`

### ISSUE THREAD

**Issue by allenhumphreys** [pvzig/SlackKit#151]
Much like `sendMessage` has `sendThreadedMessage`. There is currently no way to respond in a thread with an ephemeral message.

Alternatively, `networkInterface` could be exposed or another extension point could be added for library consumers, such as an "additionalParameters" function parameter that would allow passing in additional fields to help build the payload.

Or perhaps there's something else I missed that might allow us to do this?

**Comment by pvzig** [comment]
Without looking at the API, I would think it should be possible to add an `ephemeral` parameter on `sendThreadedMessage`?

**Comment by allenhumphreys** [comment]
I was thinking about looking at implementing this myself, but I think you’re correct. It’s just another field in the parameters that are already being sent

**Comment by pvzig** [comment]
Looks like we need to update `sendEphemeral` to support threads: https://github.com/pvzig/SlackKit/blob/master/SKWebAPI/Sources/WebAPI.swift#L318
https://api.slack.com/methods/chat.postEphemeral

**Comment by allenhumphreys** [comment]
doh! That's what I thought your earlier message meant rather than the reverse.

**Comment by pvzig** [comment]
Resolved by [PR/155](https://github.com/pvzig/SlackKit/pull/155). Thanks!
