### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by interstateone** [pvzig/SlackKit#171]
This is a feature request for pagination support for endpoints like https://api.slack.com/methods/users.list and https://api.slack.com/methods/conversations.list. This would involve the relevant methods changing to accept an optional cursor argument, and then also providing the response_metadata.next_cursor value to the success handler closure.

I have some local changes that achieve this for these two endpoints, and I could take a stab at a proper PR for this, but I wanted to get your thoughts on it first.

Thanks!

**Comment by pvzig** [comment]
Yeah better supporting pagination would be great – I think support is already there for `conversations.list` (https://github.com/pvzig/SlackKit/blob/master/SKWebAPI/Sources/WebAPI.swift#L1211) but there are definitely other `.list` calls that could use support including the generic call here: https://github.com/pvzig/SlackKit/blob/master/SKWebAPI/Sources/WebAPI.swift#L1329

**Comment by interstateone** [comment]
Ah, looks like I'm missing `conversations.list` because my origin remote is a (now outdated) fork. Thanks for mentioning that. 😄 I'll try to loop back to this at some point.
