### ISSUE TITLE
No such file or directory for "slackbot"

### ISSUE THREAD

**Issue by geraldeersteling** [pvzig/SlackKit#172]
Great work on this Kit, it works really well!  
I have some questions about deploying to Heroku though...

I've followed your [tutorial on medium](https://medium.com/@pvzig/building-slack-bots-in-swift-b99e243e444c) and got it to deploy and build on Heroku. But whenever I execute the command `heroku run:detached slackbot` in my terminal it gives me the following logs:

```
2019-11-06T11:08:45.351813+00:00 heroku[run.1261]: Starting process with command `.build/x86_64-unknown-linux/release/Threddy`
2019-11-06T11:08:46.023785+00:00 heroku[run.1261]: State changed from starting to up
2019-11-06T11:08:47.077219+00:00 heroku[run.1261]: Process exited with status 127
2019-11-06T11:08:47.120476+00:00 heroku[run.1261]: State changed from up to complete
2019-11-06T11:08:47.03261+00:00 app[run.1261]: bash: .build/release/Threddy: No such file or directory
```

> "Threddy" is my bot's name obviously 😄 

And my `Procfile` looks like:

```
web: Threddy --workers 5 --bind 0.0.0.0:$PORT
slackbot: .build/release/Threddy
```

I've got no clue how to fix this, but I've also tried changing the path to: `.build/x86_64-unknown-linux/release/Threddy`, but this fails as well.

Could someone help me out with this one?

**Comment by pvzig** [comment]
Looks like there are lots of bits of that post that aren't up-to-date any longer for 2019 and Swift 5, I'll have to try and find some time to update it again...

Specifically re: Heroku, if you're using Swift 5 you're going to want to use the [vapor buildpack](https://github.com/vapor-community/heroku-buildpack) which you can set using the Heroku CLI:

`heroku buildpacks:set vapor/vapor`

And you don't need to point to the build folder any longer – any binaries created by the build process are added to your $PATH so your Procfile would look like this:

```
web: Threddy --workers 5 --bind 0.0.0.0:$PORT
slackbot: Threddy
```

Additionally, you probably want to set the config environment variable to release:
`heroku config:set SWIFT_BUILD_CONFIGURATION=release`
