### ISSUE TITLE
Slash commands and new Slack Apps

### ISSUE THREAD

**Issue by khakionion** [pvzig/SlackKit#177]
Hello, are slash commands still expected to work with new Slack Apps? The documentation says "you can also provide slash commands as part of a Slack App," but it's not clear whether the example code is still correct for that case, nor if the token should still be the old deprecated Verification Token. 

The following code:

```
let middleware = ResponseMiddleware(token: "xoxb-bot-token", response: SKResponse(text: "👋"))
let route = RequestRoute(path: "/mycommand", middleware: middleware)
let responder = SlackKitResponder(routes: [route])
let server = SKServer(responder: responder)!
server.start()
```

...does not work for me with the following Slack app setup:
<img width="551" alt="Screen Shot 2020-02-13 at 23 00 53" src="https://user-images.githubusercontent.com/277155/74442385-c2f2e700-4eb4-11ea-8640-18db1a9703e7.png">

Running the slash command causes Slack to return the error `failed with the error "dispatch_unknown_error"` and on the SlackKit side, nothing is ever logged.

**Comment by pvzig** [comment]
Hey Michael,

The token you want for `ResponseMiddleware` isn't the bot token, it's actually the App Credentials Verification Token. You can find it under the Basic Information page for your app.

**Comment by khakionion** [comment]
I want to clarify something here...I’m making a “Slack App” using the new “2.0 OAuth 2.0” flow. I have a fully authenticated Slack App with my own Vapor-based system and no token I have works in this flow.

Once I have a modern Slack App OAuth 2.0 access token, how do I pass that to SlackKit to parse slash commands? The documentation around the new OAuth flow is minimal and there is no logging to help understand why it isn’t working. 

“Access Token” Ref: https://api.slack.com/authentication/oauth-v2

**Comment by pvzig** [comment]
I'm a bit confused. The only time you'd need a token to respond to a slash command would be if you were doing some kind of delayed response through the Web API. By default, it should just send your configured response to the response URL that the Slack API provides in the slash command payload...

Happy to try and help debug if you can provide additional details or a sample project.
