### ISSUE TITLE
Conflict when using with Realm

### ISSUE THREAD

**Issue by mbarnach** [pvzig/SlackKit#197]
When importing Realm, there is a conflict due to the name 'CORE' used by both 'Realm' and 'Vapor'.

# How to reproduce?

1. Create a new project, being an executable or a library:

```swift
swift package init --type executable
```

2. Edit the `Package.swift` to add the dependency to `SlackKit`:

   ```swift
   .package(url: "https://github.com/pvzig/SlackKit.git", .upToNextMinor(from: "4.6.0"))
   ```

   > The project is compiling fine

3. Edit the `Package.swift` to add the dependency to `Realm`:

   ```swift
   .package(name: "Realm", url: "https://github.com/realm/realm-cocoa.git", .upToNextMinor(from: "10.8.0")),
   ```

   > The project cannot compile anymore: *multiple targets named ‘Core’ in ‘core’, ‘realm-core’.

**This seems to be due to the 'Vapor' dependency inside SlackKit.**

Updating the `WebSocket` (now `websocket-kit`) of Vapor to the latest version would force to use MacOS 10.15 as target, which is probably not suitable.
So far the only solution I could come up with, is to remove completely the websocket dependency (Vapor one only).

**Comment by pvzig** [comment]
Hey Mathieu, 

Thanks for the report. Unfortunately, SPM doesn't currently handle dependency module conflicts well. Realm/Vapor should be namespacing their modules IMO - looks like there's [some](https://github.com/realm/realm-cocoa/issues/7289) [movement](https://github.com/realm/realm-core/issues/4763) on that front.

For SlackKit, I don't think it makes sense for me to remove functionality here so until those Realm changes land, you'll probably need to maintain a fork.

Cheers.
