### ISSUE TITLE
SKRTMAPI: Module not found on xcode 12.5 on Apple Silicon

### ISSUE THREAD

**Issue by farhat-nawaz** [pvzig/SlackKit#199]
I'm using xcode 12.5 on an M1 Macbook Air and I can't seem to import `SlackKit`. I'm working on a project and whenever i add `SlackKit` as dependency, my build start to fail and I can't get them back to the previous state. It starts throwing errors that roughly say a bunch of modules could not be found including `NIOOpenSSl` and `SlackKit` itself. If create a new project and add the same code, it starts working again. What might be wrong here?

**Comment by pvzig** [comment]
Hey Farhat,

Did a quick Google search and found this [thread](https://forums.swift.org/t/xcode-12-2-spm-swift-nio-fails-to-build-for-apple-silicon-arm64/42197), anything in there helpful?
