### ISSUE TITLE
How to observer changes in client?

### ISSUE THREAD

**Issue by hamin** [pvzig/SlackKit#2]
I'm a bit confused how one would observe changes on the `Client`. A callback api would be appreciated. Essentially when messages are handled my client, state changes and etc. how would one go about observing these changes in a controller?

**Comment by cbautista103** [comment]
I personally have used NSNotificationCenter to work this out... feels a bit messy but has worked reliably for me in a deployed / client situation.

**Comment by hamin** [comment]
@cbautista103 what notification messages were you observing? I don't see any NSNotificationCenter calls in the library.

**Comment by pvzig** [comment]
I'm working on adding callback hooks for specific events - check out this branch: https://github.com/pvzig/SlackKit/tree/features/callbacks

This is still very much WIP and not ready for use but I'd love to get your feedback re: does this expose what you're after?

**Comment by hamin** [comment]
@pvzig that branch is great. Its great to have a delegate api. The only issue is it would be nice to have a blocks based api too. Reason for this is might have multiple controllers that might need to listen to some or same notifications. I've done this before in a library I've written https://github.com/hamin/fayeswift . But of course an application can definitely expose this on their own. But delegates should get me most of the way there. If you want I can help submit a PR for a block based api too once you've implemented the delegate api.

**Comment by hamin** [comment]
Btw here's my hacky way of adding block based api by subclassing the slackkit client. Was trying to figure out how to know when initial setup was done...this is not that clean :)

```

import Foundation
import SlackKit
import Starscream

enum SlackClientProperty {
    case Connected, Authenticated, AuthenticatedUser, Team, Channels, Users, Bots, Files
}

typealias WebsocketDidConnect = (WebSocket) -> Void

class SLKClient: Client, PropertyObservable {
    typealias PropertyType = SlackClientProperty
    let propertyChanged = Event<SlackClientProperty>()

    private var websocketDidConnectBlocks = [WebsocketDidConnect]()

    static internal let sharedClient = SLKClient()

    override var connected: Bool {
        didSet {
            propertyChanged.raise(.Connected)
        }
    }

    override var authenticated: Bool {
        didSet {
            propertyChanged.raise(.Authenticated)
        }
    }

    override var authenticatedUser: User? {
        didSet {
            propertyChanged.raise(.AuthenticatedUser)
        }
    }

    override var team: Team? {
        didSet {
            propertyChanged.raise(.Team)
        }
    }

    override var channels: [String: Channel]? {
        didSet {
            propertyChanged.raise(.Channels)
        }
    }

    override var users: [String: User]? {
        didSet {
            propertyChanged.raise(.Users)
        }
    }

    override var bots: [String: Bot]? {
        didSet {
            propertyChanged.raise(.Bots)
        }
    }

    override var files: [String: File]? {
        didSet {
            propertyChanged.raise(.Files)
        }
    }

    func subscribeToWebsocketDidConnect(block:WebsocketDidConnect){
        self.websocketDidConnectBlocks.append(block)
    }

    override func websocketDidConnect(socket: WebSocket) {
        super.websocketDidConnect(socket)
        for cb in self.websocketDidConnectBlocks {
            cb(socket)
        }
    }

    override func websocketDidDisconnect(socket: WebSocket, error: NSError?) {
        super.websocketDidDisconnect(socket, error: error)
    }

    override func websocketDidReceiveMessage(socket: WebSocket, text: String) {
        super.websocketDidReceiveMessage(socket, text: text)
    }

    override func websocketDidReceiveData(socket: WebSocket, data: NSData) {
        super.websocketDidReceiveData(socket, data: data)
    }
}
```

**Comment by pvzig** [comment]
I'm going to close this issue as I just pushed the delegate branch to master. @hamin, I'd love to take a look at a pull request with a block-based API when you get time!

**Comment by hamin** [comment]
@pvzig awesome! I will check it out soon :)
