### ISSUE TITLE
Programmatically / Manually Disconnect

### ISSUE THREAD

**Issue by cbautista103** [pvzig/SlackKit#22]
I've been using SlackKit happily for a while now but have not found a satisfactory way to close the connection... is there a recommendation or best practice for this?

**Comment by pvzig** [comment]
This is a good idea and should be relatively simple to implement on the client - I'll take a stab at it later today.

**Comment by pvzig** [comment]
I've added disconnect support here https://github.com/pvzig/SlackKit/pull/23 and merged it down to master.

**Comment by cbautista103** [comment]
Looks great, thanks!
