### ISSUE TITLE
How can I handle error when connecting?

### ISSUE THREAD

**Issue by yoching** [pvzig/SlackKit#26]
I want to handle error when connecting.
But it seems `nil` is passed to `failure` parameter of `webAPI.rtmStart` method in `connect` function of `Client`.
https://github.com/pvzig/SlackKit/blob/master/SlackKit/Sources/Client.swift#L95

So, if error happens in `rtmStart` function ( like "no internet connection"), no message is send to delegate objects.

How can I handle webAPI error when connecting?

**Comment by pvzig** [comment]
I've added a [`clientConnectionFailed(error: SlackError)`](https://github.com/pvzig/SlackKit/pull/27/commits/30baf1f76cfe46d672b73266c35e0b79ea110cc0) method on the `SlackEventsDelegate` that gets called any time a connection or reconnection is attempted and fails.

**Comment by yoching** [comment]
Thank you very much!
