### ISSUE TITLE
Model has failable initializers, but they not return nil

### ISSUE THREAD

**Issue by michallaskowski** [pvzig/SlackKit#31]
Models (like `Client`, `Channel` and other) have failable initializers `init?`, but they do not return nil. Instead, they have all properties optional. 
I wonder if the structs could have non-failable initializers instead, which would also affect types return in success closures - the result would not be an optional. And it would be easier to deal with the result in client applications.

If you are ok with the change, I could create a new PR.

**Comment by pvzig** [comment]
Just looked at the work you've already done on your fork on this; would be happy to merge a PR when it's done.

**Comment by pvzig** [comment]
Merged here: https://github.com/pvzig/SlackKit/pull/35

**Comment by michallaskowski** [comment]
Thanks for continuing the work, I was a bit occupied and wanted to make some other minor changes this week, but it is better you already merged it. Thanks a lot!
