### ISSUE TITLE
How to simply send a msg to a channel?

### ISSUE THREAD

**Issue by sirvon** [pvzig/SlackKit#39]
thanks!

**Comment by pvzig** [comment]
Once the client is connected, you can send a message two ways; over the RTM connection, or using the web API:

RTM:
`client.sendMessage("Your message here", channelID: CHANNEL_ID)`
https://github.com/pvzig/SlackKit/blob/master/SlackKit/Sources/Client.swift#L102

Web API:
`client.webAPI.sendMessage(CHANNEL_ID, text: "Your message goes here", success: nil, failure: nil)`
https://github.com/pvzig/SlackKit/blob/master/SlackKit/Sources/SlackWebAPI.swift#L205
