### ISSUE TITLE
Objective-C

### ISSUE THREAD

**Issue by Droppix** [pvzig/SlackKit#40]
Hi, 

Do you have compatibility with Objective-C?

Thanks

**Comment by pvzig** [comment]
Hi Robert,

You absolutely can use SlackKit with Objective-C. Take a look at Apple's documentation on interoperability: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by JanC** [comment]
I'm also having troubles using the SlackKit in objective c. The generated `#import <SlackKit/SlackKit-Swift.h>` does not contain any of the SlackKit objects
