### ISSUE TITLE
CDispatch dependency

### ISSUE THREAD

**Issue by heyvito** [pvzig/SlackKit#42]
Hi there! Just tried to install SlackKit using Swift Package Manager, and your Starscream fork [declares a dependency](https://github.com/pvzig/Starscream/blob/1.0.3/Package.swift#L27) of `CDispatch`, which does not seem to be available anymore. Do you plan to update the fork, use the mainstream repository of the mentioned package, or is there a workaround on this issue?

Thanks!

**Comment by pvzig** [comment]
Hi Victor,

Looks like some of the experimentation from the Linux branch accidentally crept into the main branch, sorry about that! Installing SlackKit using the SPM should work again; let me know if you have any further issues.
