### ISSUE TITLE
SlackKit initialization with API Token

### ISSUE THREAD

**Issue by alexanderlarionov** [pvzig/SlackKit#45]
Hello!
Just updated to 2.0, migrated from previous version and faced a problem. I tried to initialize SlackKit with API Token of my bot, set the _onClientInitalization_ block, but I realized, that _onClientInitalization_ never get called. This block is **nil** in constructor body:
`public init(withAPIToken token: String, clientOptions: ClientOptions = ClientOptions()) {}`

That's why I can't get Client instance and set it's _messageEventsDelegate_. So, may be you will add _onClientInitalization_ block as a parameter to costructor, or something like this?

Thank you!

**Comment by pvzig** [comment]
Hey Alex,

Make sure that you're using at least version `2.0.2` as there was a bug in the initial `2.0.0` release where the initialization block never got called when using a manual token.

If you're using `2.0.2`, following this pattern should work:
```
let bot = SlackKit(withAPIToken: "xoxb-YOUR-TOKEN-HERE")
bot.onClientInitalization = { (client: Client) in
    dispatch_async(dispatch_get_main_queue(), {
        //Register for any callbacks you need here like connection events
        client.connectionEventsDelegate = self
    })
```

**Comment by alexanderlarionov** [comment]
Now it's fine, thank you!
