### ISSUE TITLE
Disable Caching

### ISSUE THREAD

**Issue by MarcusSmith** [pvzig/SlackKit#49]
It looks like SlackKit is caching every piece of information it sends / receives.  For building a slackbot with SlackKit, I would not want it to hold all of this information in memory for its whole lifetime.   

Could SlackKit have an option to disable this caching?

**Comment by pvzig** [comment]
In version 4 you can disable caching by passing `nil` to the `client` param.
```
let bot = SlackKit()
bot.addRTMBotWithAPIToken(“xoxb-SLACK_AUTH_TOKEN”, client: nil)
```
