### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by TofPlay** [pvzig/SlackKit#50]
Hi
Below the title please add badges for carthage compatibility, SwiftPM compatibility,  pod version, Swift version, license and platform like this:
[![Carthage compatible](https://img.shields.io/badge/Carthage-compatible-brightgreen.svg)](https://github.com/Carthage/Carthage) [![SwiftPM compatible](https://img.shields.io/badge/SwiftPM-compatible-brightgreen.svg)](https://github.com/apple/swift-package-manager) ![Pod Version](https://img.shields.io/badge/Pod-2.0.0-blue.svg) ![Swift Version](https://img.shields.io/badge/Swift-2.2-orange.svg) ![License MIT](https://img.shields.io/badge/License-MIT-lightgrey.svg) ![Plaforms](https://img.shields.io/badge/Platforms-macOS,iOS,tvOS-lightgrey.svg)

**Comment by pvzig** [comment]
Done, thanks!
