### ISSUE TITLE
SlackKit uses up an integration towards the quota?

### ISSUE THREAD

**Issue by avaidyam** [pvzig/SlackKit#56]
Is there a way to design an application client that _doesn't_ use up an app integration towards the team's quota? It looks like that's the only way right now.

**Comment by pvzig** [comment]
Hi Aditya,

You could use SlackKit to create additional webhooks, slash commands, or custom bot users without using up an app integration. I believe each of those custom integration types only counts as one integration (https://twitter.com/SlackHQ/status/786226860967550977). Each OAuthed app does count as an additional integration.

Peter
