### ISSUE TITLE
Channel and User objects are empty in userTypingIn delegate method

### ISSUE THREAD

**Issue by Drarok** [pvzig/SlackKit#57]
I'm using following code, having connected successfully:

```
func userTypingIn(_ channel: Channel, user: User, client: Client) {
    print("userTypingIn \(channel.name): \(user.name)")
}
```

However, in my logs, all I see is the following:

```
userTypingIn nil: nil
```

**Comment by Drarok** [comment]
I've also tried the following, which almost works:

```
    guard let cid = channel.id, let c = client.channels[cid] else {
        print("userTypingIn failed to identify channel")
        return
    }

    guard let uid = user.id, let u = client.users[uid] else {
        print("userTypingIn failed to identify user")
        return
    }

    print("userTypingIn \(c.name): \(u.name)")
```

It results in the following:

```
userTypingIn nil: Optional("drarok")
```

Edit: Ah, this was because I wasn't in a channel, but a private chat. Fetching the channel and user from the Client object does work, but seems unnecessary.

**Comment by pvzig** [comment]
Hi Mat,

Glad you figured it out. The reason you're having to pull the values from the client by id is that the channel/user id is all that's returned from the API (https://api.slack.com/events/user_typing) and there's no guarantee that those objects have been cached locally.

That being said, the delegate API here should reflect the fact that it's simply passing ids and not fully formed objects. It's just about the oldest part of the code base at this point and I'm looking forward to finding some time to get in there and clean it up. Thanks for the report!

Peter
