### ISSUE TITLE
Can we have 'send' to Throw or return an error?

### ISSUE THREAD

**Issue by alimoeeny** [pvzig/SlackKit#74]
Is it possible to have `client.send(message: String, channelID: String)` either `throw` or return an error?

**Comment by pvzig** [comment]
It should certainly `throw`. Thanks for the issue!

**Comment by pvzig** [comment]
In v4, sending from RTM now throws: https://github.com/SlackKit/SKRTMAPI/blob/master/Sources/SKRTMAPI/SKRTMAPI.swift#L92
