### ISSUE TITLE
Is it me or the pod is broken

### ISSUE THREAD

**Issue by alimoeeny** [pvzig/SlackKit#76]
Did a `pod update`  today and got bumped from `3.1.5` to `3.1.8` 
But the `pods/SlackKit` folder only contains the LICENSE and README.md files and nothing else.

I guess this commit 051e8dd6c8ec561506cf6b0710f6aad1f923a250 removed the source reference and broke the pod, or am I missing something?

**Comment by pvzig** [comment]
Not you, I broke the podspec. Fixed in [3.1.9](https://github.com/pvzig/SlackKit/releases/tag/3.1.9).

`pod repo update` 
`pod update`

And you should be good to go.

Thanks for the issue!
