### ISSUE TITLE
API Token usage against free Slack integration quota?

### ISSUE THREAD

**Issue by avaidyam** [pvzig/SlackKit#79]
Is it likely that using a dev API token will be counted as one of five (?) free integrations on a free Slack team's accounts?

**Comment by pvzig** [comment]
Yes, I believe it does (the limit for free plans is now 10 integrations). If you need to know for sure, tweet [@slackapi](https://www.twitter.com/slackapi), they should be able to give you an answer.

**Comment by avaidyam** [comment]
I think I just got the response from their Support team!
> The Slack API tester does not count against the free team limit of 10 integrations.
