### ISSUE TITLE
No means to get channel history

### ISSUE THREAD

**Issue by simonmcl** [pvzig/SlackKit#8]
Kit doesn't have a means to get the [channel history](https://api.slack.com/methods/channels.history) and load it into the client object

**Comment by pvzig** [comment]
SlackKit currently just consumes Slack's Real Time Messaging API which doesn't provide a hook to get channel history. I'm slowly working on adding support for the web API on this branch, which would include `channels.history`: https://github.com/pvzig/SlackKit/tree/web-api

**Comment by simonmcl** [comment]
ah ok cool, thanks. I'll close this so
