### ISSUE TITLE
AppDelegate Does Not Conform To Protocol SlackEventsDelegate

### ISSUE THREAD

**Issue by sirvon** [pvzig/SlackKit#81]
I keep getting this error
and I've implemented all the methods from that protocol.

What gives....

```swift
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate, MessageEventsDelegate,ConnectionEventsDelegate, SlackEventsDelegate{
    func preferenceChanged(_ preference: String, value: Any?, client: Client){print(client)}
    func userChanged(_ user: User, client: Client){print(client)}
    func presenceChanged(_ user: User, presence: String, client: Client){print(client)}
    func manualPresenceChanged(_ user: User, presence: String, client: Client){print(client)}
    func botEvent(_ bot: Bot, client: Client){print(client)}
    public func userTypingIn(_ channel: Channel, user: User, client: Client) {
        print(user)
    }
```

the other protocols' methods have been implemented in below un posted code...

**Comment by pvzig** [comment]
Hi Sirvon,

Your code compiles without errors for me using SlackKit 3.1.9 with Xcode 8.2.1.

`Does not conform to protocol` errors can only mean that your declared functions don't match what the compiler is expecting to see. Cmd clicking on the delegate declaration will take you to the underlying implementation. Matching that will make this error go away.
