### ISSUE TITLE
How to pass around client object throughout app?

### ISSUE THREAD

**Issue by sirvon** [pvzig/SlackKit#82]
```swift
bot.onClientInitalization = { (client: Client) in
            DispatchQueue.main.async(execute: {
                client.messageEventsDelegate = self
                client.connectionEventsDelegate = self
                //send client to object cache? 
                //put client somewhere to use it again elsewhere or
               // try another design?
            })
```

or should i really be doing webAPI stuff here...
```swift
    func connected(_ client: Client) {
        print("\(client.connected) \("connected FromForeground")")
        //send client to object cache? 
        //put client somewhere to use it again elsewhere or
        // try another design?
    }

```
I see there's a few ways to get the initialized client object so that I can call WebAPI.
But how can I pass this object around the app and use it anywhere in the app?

Or is it cool to just do initialization again anywhere when I need the client object?

**Comment by pvzig** [comment]
Hey Sirvon,

Without knowing exactly what you're trying to do it's hard to know what exactly the right approach would be but you have a few options:

1. If you're responding to the initialization event, you can use the `Client` object that's passed via that closure. 
2. If you're responding to a specific event, almost all of the delegate methods send a `Client` instance that you can use.
3. If you need to make requests independent of these situations, you can [initalize your own instance](https://github.com/pvzig/SlackKit/blob/master/Sources/SlackKit/WebAPI.swift#L113) of `WebAPI`
