### ISSUE TITLE
Swifter only compiles on version 1

### ISSUE THREAD

**Issue by ryancstack** [pvzig/SlackKit#85]
Updating to version 3 breaks build

**Comment by pvzig** [comment]
Whoops, I updated the dependencies with the wrong path. Fixed in [3.1.10](https://github.com/pvzig/SlackKit/releases/tag/3.1.10).

**Comment by ryancstack** [comment]
Swifter pointing to 1.3.3 breaks build. Swifter should point to 1.1.3

**Comment by pvzig** [comment]
Are you trying to build the project or trying to build it as a dependency? And SPM, CocoaPods, or Carthage?

**Comment by ryancstack** [comment]
Building as a dependency with SPM

**Comment by pvzig** [comment]
Fixed in [3.1.11](https://github.com/pvzig/SlackKit/releases/tag/3.1.11), sorry about that.
