### ISSUE TITLE
Slash Command Implementation

### ISSUE THREAD

**Issue by thisisalexmcgregor** [pvzig/SlackKit#86]
Hello!

Is there an example anywhere demonstrating how to properly setup a slash command? I'm looking into using `SlackKit` for this side project and I'm happy to append documentation and submit a PR. What exactly is the `route`? When initializing the `WebhookServer`? The token I'm assuming is the `Verification Token` for your app. I'm using ngrok for now FYI. 

Thanks for your help.

**Comment by pvzig** [comment]
Hey Alex,

You'll need to create a `WebhookServer` with a token, a route, and a response:

```
let response = Response(text: "Hello, World!", responseType: .inChannel)
let webhook = WebhookServer(token: "SLASH-COMMAND-TOKEN", route: "hello", response: response)
webhook.start()
```

The route is the http route that will be called. If your url was `https://b4af9fce.ngrok.io` for instance, you would want to point your Slash command at `https://b4af9fce.ngrok.io/hello` when configuring it in Slack in this example:

<img width="580" alt="screen shot 2017-03-22 at 8 03 57 pm" src="https://cloud.githubusercontent.com/assets/8311605/24226144/19404f60-0f3b-11e7-8abd-4ba10ffaec04.png">

For the token you want to use the `Verification Token` under `Basic Information` for your Slack app:

<img width="792" alt="screen shot 2017-03-22 at 8 04 30 pm" src="https://cloud.githubusercontent.com/assets/8311605/24226138/1591292a-0f3b-11e7-87ef-81d2ae9125a4.png">

**Comment by thisisalexmcgregor** [comment]
@pvzig awesome! I'll take a look tomorrow morning. Appreciate the response. 💯🎉
