### ISSUE TITLE
Channel entrance/exit event changes

### ISSUE THREAD

**Issue by pvzig** [pvzig/SlackKit#98]
- [Changelog: Channel entrance/exit events](https://api.slack.com/changelog/2017-05-rethinking-channel-entrance-and-exit-events-and-messages)

**Comment by allenhumphreys** [comment]
I really need this!

**Comment by pvzig** [comment]
Added in [4.2.2](https://github.com/pvzig/SlackKit/releases/tag/4.2.2)

**Comment by allenhumphreys** [comment]
Thank you so much @pvzig, I'll be adding channel welcome messages now!!
